version: "3"

services:
    web:
        build: ./app
        command: gunicorn lovelysad.wsgi:application --bind 0.0.0.0:8000
        ports:
            - 8000:8000
        env_file:
            - ./.env.prod
        depends_on:
            - db
            
    db:
        image: mysql
        ports:
            - 3306:3306
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_USER: ls
            MYSQL_PASSWORD: lspass
            MYSQL_DATABASE: lovelysad
        volumes:
            - ./app/db/lovelysad.sql:/docker-entrypoint-initdb.d/lovelysad.sql
            - db_data:/var/lib/mysql
            
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./app/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./app/ls:/var/www
        depends_on:
            - web
        
volumes:
    db_data:
