# Generated by Django 3.2.7 on 2021-12-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veg_type', models.CharField(max_length=50, verbose_name='Культура')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='ls/static/ls/images/%Y-%m-%d')),
            ],
        ),
    ]
