# Generated by Django 3.2.7 on 2021-12-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetables',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
