# Generated by Django 3.2.7 on 2021-12-23 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0002_alter_vegetables_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tomato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Сорт')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ls.vegetables')),
            ],
        ),
    ]
