# Generated by Django 3.2.7 on 2021-12-23 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0003_tomato'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomato',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tomato',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
