# Generated by Django 3.2.7 on 2021-12-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0006_tomato_tomato_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomato',
            name='tomato_color',
            field=models.CharField(default='Красный', max_length=50, verbose_name='Сорт'),
        ),
    ]
