# Generated by Django 3.2.7 on 2021-12-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0007_tomato_tomato_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomato',
            name='tomato_type',
            field=models.CharField(blank=True, choices=[('Детерминантный', 'Детерминантный'), ('Индетерминантный', 'Индетерминантный'), ('Полудетерминантный', 'Полудетерминантный'), ('Штамбовый', 'Штамбовый'), ('Ампельный', 'Ампельный')], max_length=50),
        ),
    ]
