# Generated by Django 3.2.7 on 2021-12-24 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0008_alter_tomato_tomato_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tomato',
            options={'verbose_name': 'Томаты', 'verbose_name_plural': 'Томаты'},
        ),
        migrations.AlterModelOptions(
            name='vegetables',
            options={'verbose_name': 'Овощи', 'verbose_name_plural': 'Овощи'},
        ),
        migrations.AlterField(
            model_name='tomato',
            name='t_id',
            field=models.ForeignKey(default='Томаты', on_delete=django.db.models.deletion.CASCADE, to='ls.vegetables'),
        ),
        migrations.AlterField(
            model_name='tomato',
            name='tomato_color',
            field=models.CharField(default='Красный', max_length=50, verbose_name='Цвет плода'),
        ),
    ]
