# Generated by Django 3.2.7 on 2021-12-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0009_auto_20211224_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetables',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y-%m-%d'),
        ),
    ]
