# Generated by Django 3.2.7 on 2021-12-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0010_alter_vegetables_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomato',
            name='image',
            field=models.ImageField(blank=True, upload_to='ls/images/tomato/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='vegetables',
            name='image',
            field=models.ImageField(blank=True, upload_to='ls/images/%Y-%m-%d'),
        ),
    ]
