# Generated by Django 3.2.7 on 2021-12-27 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0014_auto_20211227_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomato',
            name='t_id',
            field=models.ForeignKey(default='Томаты', on_delete=django.db.models.deletion.CASCADE, to='ls.vegetables', verbose_name='Культура'),
        ),
    ]
