# Generated by Django 3.2.7 on 2021-12-27 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0016_flowers_flowers_sorts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowers_sorts',
            options={'verbose_name': 'Сорта цветов', 'verbose_name_plural': 'Сорта цветов'},
        ),
    ]
