# Generated by Django 3.2.7 on 2021-12-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0018_auto_20211227_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomato',
            name='tomato_grunt',
            field=models.CharField(blank=True, choices=[('Открытый грунт', 'Открытый грунт'), ('Закрытый грунт', 'Закрытый грунт'), ('Открытый и закрытый грунт', 'Открытый и закрытый грунт')], max_length=50, verbose_name='Способ выращивания'),
        ),
    ]
