# Generated by Django 3.2.7 on 2021-12-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0021_alter_kapusta_t_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kapusta',
            name='goal',
            field=models.CharField(blank=True, max_length=300, verbose_name='Назначение'),
        ),
    ]
