# Generated by Django 3.2.7 on 2021-12-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0022_alter_kapusta_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='kapusta',
            name='vids_image',
            field=models.CharField(default='ls/images/kapusta/noimage.jpg', max_length=100),
        ),
    ]
