# Generated by Django 3.2.7 on 2021-12-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0024_alter_kapusta_vids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tomato',
            old_name='tomato_type',
            new_name='vids',
        ),
        migrations.AddField(
            model_name='tomato',
            name='vids_image',
            field=models.CharField(default='ls/images/tomato/noimage.jpg', max_length=100),
        ),
    ]
