# Generated by Django 3.2.7 on 2022-01-04 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0027_auto_20211230_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baklajan',
            old_name='grunt',
            new_name='grunt_type',
        ),
        migrations.RenameField(
            model_name='baklajan',
            old_name='type',
            new_name='type_kusta',
        ),
        migrations.RenameField(
            model_name='kapusta',
            old_name='grunt',
            new_name='grunt_type',
        ),
        migrations.RenameField(
            model_name='perets',
            old_name='perets_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='perets',
            old_name='perets_form',
            new_name='form',
        ),
        migrations.RenameField(
            model_name='perets',
            old_name='perets_goal',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='perets',
            old_name='perets_grunt',
            new_name='grunt_type',
        ),
        migrations.RenameField(
            model_name='perets',
            old_name='perets_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='perets',
            old_name='perets_sort',
            new_name='sort',
        ),
        migrations.RenameField(
            model_name='perets',
            old_name='perets_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='perets',
            old_name='perets_type',
            new_name='type_kusta',
        ),
        migrations.RenameField(
            model_name='tomato',
            old_name='tomato_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='tomato',
            old_name='tomato_form',
            new_name='form',
        ),
        migrations.RenameField(
            model_name='tomato',
            old_name='tomato_goal',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='tomato',
            old_name='tomato_grunt',
            new_name='grunt_type',
        ),
        migrations.RenameField(
            model_name='tomato',
            old_name='tomato_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='tomato',
            old_name='tomato_sort',
            new_name='sort',
        ),
        migrations.RenameField(
            model_name='tomato',
            old_name='tomato_time',
            new_name='time',
        ),
    ]
