# Generated by Django 4.0.1 on 2022-01-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0028_auto_20220104_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baklajan',
            name='form',
            field=models.CharField(blank=True, max_length=100, verbose_name='Форма плода'),
        ),
        migrations.AlterField(
            model_name='tomato',
            name='form',
            field=models.CharField(blank=True, max_length=100, verbose_name='Форма плода'),
        ),
    ]
