# Generated by Django 4.0.1 on 2022-01-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0029_alter_baklajan_form_alter_tomato_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='baklajan',
            name='veg_type',
            field=models.CharField(default='Баклажаны', max_length=100, verbose_name='Культура'),
        ),
        migrations.AddField(
            model_name='tomato',
            name='veg_type',
            field=models.CharField(default='Томаты', max_length=100, verbose_name='Культура'),
        ),
    ]
