# Generated by Django 4.0.1 on 2022-01-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0030_baklajan_veg_type_tomato_veg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='baklajan',
            name='vids',
            field=models.CharField(max_length=50, null=True, verbose_name='Тип куста'),
        ),
    ]
