# Generated by Django 4.0.1 on 2022-01-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0031_baklajan_vids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perets',
            name='type_kusta',
            field=models.CharField(blank=True, choices=[('Высокорослые', 'Высокорослые'), ('Низкорослые', 'Низкорослые'), ('Штамбовые', 'Штамбовые')], max_length=50, verbose_name='Тип куста'),
        ),
        migrations.AlterField(
            model_name='perets',
            name='vids',
            field=models.CharField(blank=True, choices=[('Сладкие', 'Сладкие'), ('Острые', 'Острые')], max_length=50, verbose_name='Вид перца'),
        ),
        migrations.AlterField(
            model_name='tomato',
            name='vids',
            field=models.CharField(blank=True, choices=[('Детерминантные', 'Детерминантные'), ('Индетерминантные', 'Индетерминантные'), ('Полудетерминантные', 'Полудетерминантные'), ('Штамбовые', 'Штамбовые'), ('Ампельные', 'Ампельные')], max_length=50, verbose_name='Тип куста'),
        ),
    ]
