# Generated by Django 4.0.1 on 2022-01-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0032_alter_perets_type_kusta_alter_perets_vids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kapusta',
            name='veg_type',
            field=models.CharField(default='Капуста', max_length=100, verbose_name='Культура'),
        ),
        migrations.AddField(
            model_name='perets',
            name='veg_type',
            field=models.CharField(default='Перцы', max_length=100, verbose_name='Культура'),
        ),
    ]
