# Generated by Django 4.0.1 on 2022-01-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0033_kapusta_veg_type_perets_veg_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cucumber',
            old_name='opyl',
            new_name='vids',
        ),
        migrations.AddField(
            model_name='cucumber',
            name='veg_type',
            field=models.CharField(default='Огурцы', max_length=100, verbose_name='Культура'),
        ),
        migrations.AddField(
            model_name='morkov',
            name='veg_type',
            field=models.CharField(default='Морковь', max_length=100, verbose_name='Культура'),
        ),
        migrations.AddField(
            model_name='morkov',
            name='vids',
            field=models.CharField(max_length=50, null=True, verbose_name='Тип куста'),
        ),
        migrations.AddField(
            model_name='redis',
            name='veg_type',
            field=models.CharField(default='Редис', max_length=100, verbose_name='Культура'),
        ),
        migrations.AddField(
            model_name='redis',
            name='vids',
            field=models.CharField(max_length=50, null=True, verbose_name='Тип куста'),
        ),
        migrations.AddField(
            model_name='svekla',
            name='veg_type',
            field=models.CharField(default='Свекла', max_length=100, verbose_name='Культура'),
        ),
        migrations.AddField(
            model_name='svekla',
            name='vids',
            field=models.CharField(max_length=50, null=True, verbose_name='Тип куста'),
        ),
        migrations.AlterField(
            model_name='baklajan',
            name='name',
            field=models.CharField(default='Баклажан ', max_length=500, verbose_name='Сорт'),
        ),
        migrations.AlterField(
            model_name='cucumber',
            name='name',
            field=models.CharField(default='Огурец ', max_length=500, verbose_name='Сорт'),
        ),
        migrations.AlterField(
            model_name='kapusta',
            name='name',
            field=models.CharField(default='Капуста ', max_length=500, verbose_name='Сорт'),
        ),
        migrations.AlterField(
            model_name='morkov',
            name='name',
            field=models.CharField(default='Морковь ', max_length=500, verbose_name='Сорт'),
        ),
        migrations.AlterField(
            model_name='perets',
            name='name',
            field=models.CharField(default='Перец ', max_length=500, verbose_name='Сорт'),
        ),
        migrations.AlterField(
            model_name='redis',
            name='name',
            field=models.CharField(default='Редис ', max_length=500, verbose_name='Сорт'),
        ),
        migrations.AlterField(
            model_name='svekla',
            name='name',
            field=models.CharField(default='Свекла ', max_length=500, verbose_name='Сорт'),
        ),
        migrations.AlterField(
            model_name='tomato',
            name='name',
            field=models.CharField(default='Томат ', max_length=500, verbose_name='Сорт'),
        ),
    ]
