# Generated by Django 4.0.1 on 2022-01-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0035_alter_cucumber_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perets',
            name='color',
            field=models.CharField(blank=True, max_length=150, verbose_name='Цвет плода'),
        ),
    ]
