# Generated by Django 4.0.1 on 2022-01-30 03:25

from django.db import migrations, models
import ls.models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0037_alter_svekla_name_alter_svekla_t_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svekla',
            name='name',
            field=models.CharField(default=ls.models.Svekla.get_default, max_length=500, verbose_name='Сорт'),
        ),
    ]
