# Generated by Django 4.0.1 on 2022-01-30 03:30

from django.db import migrations, models
import django.db.models.deletion
import ls.models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0038_alter_svekla_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baklajan',
            name='veg_type',
            field=models.CharField(default=ls.models.Baklajan.get_default, max_length=100, verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='cucumber',
            name='t_id',
            field=models.ForeignKey(default=ls.models.Cucumber.get_default, on_delete=django.db.models.deletion.CASCADE, to='ls.vegetables', verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='cucumber',
            name='veg_type',
            field=models.CharField(default=ls.models.Cucumber.get_default, max_length=100, verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='kapusta',
            name='veg_type',
            field=models.CharField(default=ls.models.Kapusta.get_default, max_length=100, verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='morkov',
            name='t_id',
            field=models.ForeignKey(default=ls.models.Morkov.get_default, on_delete=django.db.models.deletion.CASCADE, to='ls.vegetables', verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='morkov',
            name='veg_type',
            field=models.CharField(default=ls.models.Morkov.get_default, max_length=100, verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='perets',
            name='veg_type',
            field=models.CharField(default=ls.models.Perets.get_default, max_length=100, verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='redis',
            name='t_id',
            field=models.ForeignKey(default=ls.models.Redis.get_default, on_delete=django.db.models.deletion.CASCADE, to='ls.vegetables', verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='redis',
            name='veg_type',
            field=models.CharField(default=ls.models.Redis.get_default, max_length=100, verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='svekla',
            name='name',
            field=models.CharField(default='Свекла ', max_length=500, verbose_name='Сорт'),
        ),
        migrations.AlterField(
            model_name='tomato',
            name='t_id',
            field=models.ForeignKey(default=ls.models.Tomato.get_default, on_delete=django.db.models.deletion.CASCADE, to='ls.vegetables', verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='tomato',
            name='veg_type',
            field=models.CharField(default=ls.models.Tomato.get_default, max_length=100, verbose_name='Культура'),
        ),
    ]
