# Generated by Django 4.0.1 on 2022-01-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0039_alter_baklajan_veg_type_alter_cucumber_t_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morkov',
            name='sort_type',
            field=models.CharField(blank=True, choices=[('Берликум', 'Берликум'), ('Нантская', 'Нантская'), ('Шантане', 'Шантане'), ('Флакке', 'Флакке')], max_length=50, verbose_name='Сортотип'),
        ),
    ]
