# Generated by Django 4.0.1 on 2022-01-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0040_alter_morkov_sort_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cucumber',
            name='vids_image',
            field=models.CharField(default='ls/images/cucumber/noimage.jpg', max_length=100),
        ),
    ]
