# Generated by Django 4.0.1 on 2022-02-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0041_cucumber_vids_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomato',
            name='vids_description',
            field=models.TextField(blank=True, verbose_name='Тип куста (описание)'),
        ),
    ]
