# Generated by Django 4.0.1 on 2022-02-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0042_tomato_vids_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cucumber',
            name='vids_description',
            field=models.TextField(blank=True, verbose_name='Тип перцев (описание)'),
        ),
        migrations.AddField(
            model_name='perets',
            name='vids_description',
            field=models.TextField(blank=True, verbose_name='Тип перцев (описание)'),
        ),
    ]
