# Generated by Django 4.0.1 on 2022-02-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0043_cucumber_vids_description_perets_vids_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='kapusta',
            name='vids_description',
            field=models.TextField(blank=True, verbose_name='Вид капусты (описание)'),
        ),
    ]
