# Generated by Django 4.0.1 on 2022-02-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0044_kapusta_vids_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cucumber',
            name='vids',
            field=models.CharField(blank=True, choices=[('Пчелоопыляемые', 'Пчелоопыляемые'), ('Партенокарпики (самоопыляемые)', 'Партенокарпики (самоопыляемые)')], max_length=50, verbose_name='Тип опыления'),
        ),
    ]
