# Generated by Django 4.0.1 on 2022-02-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0045_alter_cucumber_vids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toSortName', models.CharField(max_length=500, verbose_name='Сорт')),
                ('authorName', models.CharField(max_length=50, verbose_name='Имя')),
                ('authorEmail', models.EmailField(max_length=50, verbose_name='Email')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Комментарии и отзывы',
                'verbose_name_plural': 'Комментарии и отзывы',
            },
        ),
    ]
