# Generated by Django 4.0.1 on 2022-02-20 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0047_comments_approved_comments_pub_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='UserComments',
        ),
    ]
