# Generated by Django 4.0.1 on 2022-02-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0048_rename_comments_usercomments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserComments',
        ),
    ]
