# Generated by Django 4.0.1 on 2022-02-20 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0049_delete_usercomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toSortName', models.CharField(max_length=500, verbose_name='Сорт')),
                ('authorName', models.CharField(max_length=50, verbose_name='Имя')),
                ('authorEmail', models.EmailField(max_length=50, verbose_name='Email')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('approved', models.BooleanField(default=False, verbose_name='Одобрено')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
            ],
            options={
                'verbose_name': 'Комментарии и отзывы',
                'verbose_name_plural': 'Комментарии и отзывы',
            },
        ),
    ]
