# Generated by Django 4.0.1 on 2022-02-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0050_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cucumber',
            name='vids_description',
        ),
        migrations.RemoveField(
            model_name='cucumber',
            name='vids_image',
        ),
        migrations.AddField(
            model_name='cucumber',
            name='opylenie',
            field=models.CharField(blank=True, choices=[('Пчелоопыляемые', 'Пчелоопыляемые'), ('Самоопыляемые', 'Самоопыляемые'), ('Партенокарпики', 'Партенокарпики')], max_length=50, verbose_name='Тип опыления'),
        ),
        migrations.AlterField(
            model_name='cucumber',
            name='vids',
            field=models.CharField(max_length=50, null=True, verbose_name='Тип куста'),
        ),
    ]
