# Generated by Django 4.0.1 on 2022-02-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0051_remove_cucumber_vids_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cucumber',
            name='opylenie',
            field=models.CharField(blank=True, choices=[('Пчелоопыляемый', 'Пчелоопыляемый'), ('Самоопыляемый', 'Самоопыляемый'), ('Партенокарпик', 'Партенокарпик')], max_length=50, verbose_name='Тип опыления'),
        ),
    ]
