# Generated by Django 4.0.1 on 2022-02-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0052_alter_cucumber_opylenie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cucumber',
            name='vids',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип куста'),
        ),
    ]
