# Generated by Django 4.0.1 on 2022-02-27 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0053_alter_cucumber_vids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cucumber',
            name='vids',
        ),
    ]
