# Generated by Django 4.0.1 on 2022-02-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0054_remove_cucumber_vids'),
    ]

    operations = [
        migrations.AddField(
            model_name='cucumber',
            name='vids',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип куста'),
        ),
    ]
