# Generated by Django 4.0.1 on 2022-02-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0055_cucumber_vids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cucumber',
            name='vids',
            field=models.CharField(max_length=50, null=True, verbose_name='Тип куста'),
        ),
    ]
