# Generated by Django 4.0.1 on 2022-02-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0056_alter_cucumber_vids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cucumber',
            name='opylenie',
        ),
        migrations.AlterField(
            model_name='cucumber',
            name='vids',
            field=models.CharField(choices=[('Пчелоопыляемый', 'Пчелоопыляемый'), ('Самоопыляемый', 'Самоопыляемый'), ('Партенокарпик', 'Партенокарпик')], default='Самоопыляемый', max_length=50, verbose_name='Тип'),
        ),
    ]
