# Generated by Django 4.0.1 on 2022-04-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0057_remove_cucumber_opylenie_alter_cucumber_vids'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='class_image',
            field=models.CharField(default='/static/ls/images/flowers_all.jpg', max_length=100, verbose_name='Фото категории'),
        ),
        migrations.AddField(
            model_name='flowers',
            name='color',
            field=models.CharField(default='', max_length=50, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='flowers',
            name='dlinapobegov',
            field=models.CharField(default=' см', max_length=50, verbose_name='Длина побегов'),
        ),
        migrations.AddField(
            model_name='flowers',
            name='height',
            field=models.CharField(default=' см', max_length=50, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='flowers',
            name='name',
            field=models.CharField(default='', max_length=500, verbose_name='Сорт'),
        ),
        migrations.AddField(
            model_name='flowers',
            name='sozvetie',
            field=models.CharField(default=' см', max_length=50, verbose_name='Соцветие'),
        ),
        migrations.AddField(
            model_name='flowers',
            name='tsvetok',
            field=models.CharField(default=' см', max_length=50, verbose_name='Цветок'),
        ),
        migrations.AddField(
            model_name='flowers',
            name='vid',
            field=models.CharField(default='', max_length=500, verbose_name='Вид'),
        ),
        migrations.DeleteModel(
            name='Flowers_sorts',
        ),
    ]
