# Generated by Django 4.0.1 on 2022-04-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0058_flowers_class_image_flowers_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='dlinapobegov',
            field=models.CharField(blank=True, default=' см', max_length=50, verbose_name='Длина побегов'),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='height',
            field=models.CharField(blank=True, default=' см', max_length=50, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='lifetime',
            field=models.CharField(blank=True, max_length=50, verbose_name='Время жизни'),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='sozvetie',
            field=models.CharField(blank=True, default=' см', max_length=50, verbose_name='Соцветие'),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='tsvetok',
            field=models.CharField(blank=True, default=' см', max_length=50, verbose_name='Цветок'),
        ),
    ]
