# Generated by Django 4.0.1 on 2022-04-08 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0060_alter_flowers_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flowers',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
