# Generated by Django 4.0.1 on 2022-04-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0061_flowers_likes_flowers_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='vid_image',
            field=models.CharField(default='/static/ls/images/noimage.jpg', max_length=100, verbose_name='Фото вида'),
        ),
    ]
