# Generated by Django 4.0.1 on 2022-04-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0062_flowers_vid_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='class_image',
            field=models.CharField(default='/ls/images/flowers_all.jpg', max_length=100, verbose_name='Фото категории'),
        ),
    ]
