# Generated by Django 4.0.1 on 2022-04-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0063_alter_flowers_class_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='class_image',
            field=models.CharField(default='/static/ls/images/flowers_all.jpg', max_length=100, verbose_name='Фото категории'),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='vid_image',
            field=models.CharField(default='ls/images/noimage.jpg', max_length=100, verbose_name='Фото вида'),
        ),
    ]
