# Generated by Django 4.0.1 on 2022-04-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0064_alter_flowers_class_image_alter_flowers_vid_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='vid_image',
            field=models.CharField(max_length=100, verbose_name='Фото вида'),
        ),
    ]
