# Generated by Django 4.0.1 on 2022-04-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0066_alter_flowers_vid_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='veg_type',
            field=models.CharField(default='Цветы', max_length=100, verbose_name='Культура'),
        ),
        migrations.AddField(
            model_name='flowers',
            name='vids',
            field=models.CharField(max_length=50, null=True, verbose_name='Ненужное'),
        ),
    ]
