# Generated by Django 4.0.1 on 2022-04-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0067_flowers_veg_type_flowers_vids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowers',
            name='vid',
        ),
        migrations.AlterField(
            model_name='flowers',
            name='vids',
            field=models.CharField(default='', max_length=500, verbose_name='Вид'),
        ),
    ]
