# Generated by Django 4.0.1 on 2022-04-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0068_remove_flowers_vid_alter_flowers_vids'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='vid_descr',
            field=models.CharField(default='', max_length=100, verbose_name='Описание вида'),
        ),
    ]
