# Generated by Django 4.0.1 on 2022-04-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0069_flowers_vid_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='vid_descr',
            field=models.CharField(blank=True, max_length=100, verbose_name='Описание вида'),
        ),
    ]
